name: "Deploy to AWS"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy to AWS"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Terraform
        run: |
          curl -o /tmp/terraform.zip -LO https://releases.hashicorp.com/terraform/1.3.5/terraform_1.4.6_linux_amd64.zip
          unzip /tmp/terraform.zip
          chmod +x terraform && mv terraform /usr/local/bin/

      - name: terraform cloud credential
        run: base64 --decode <<< ${{ secrets.TERRAFORM_CLOUD_CREDENTIAL }} > ~/.terraformrc

      - name: aws credential
        run: |
          mkdir ~/.aws
          base64 --decode <<< ${{ secrets.AWS_CRED }} > ~/.aws/credentials
          base64 --decode <<< ${{ secrets.AWS_CONFIG }} > ~/.aws/config

      - run: terraform init
      - run: terraform apply -auto-approve 1> /dev/null
